// <auto-generated />
namespace ASPNet_API_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class aaaa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aaaa));
        
        string IMigrationMetadata.Id
        {
            get { return "202102220902288_aaaa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
